### ISSUE TITLE
Add support for the Interface Builder attribute @IBDesignable

### ISSUE THREAD

**Issue by Adobels** [grigorievs/SGCodeTextField#1]
As a user of the Interface Builder, I would like to be able to set a @IBInspectable properties of the SGCodeTextField object and render the resulting view in a view editor.

**Comment by grigorievs** [comment]
on it.

**Comment by grigorievs** [comment]
Fixed in [PR4](https://github.com/grigorievs/SGCodeTextField/pull/4)
